services:
  - type: web
    name: rickorty-visual-novel
    runtime: python3
    buildCommand: pip install -r requirements-render.txt
    startCommand: python server.py
    envVars:
      - key: CHUTES_API_KEY
        sync: false
    autoDeploy: false